version: "3.7"
 
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.dev
      target: base
    volumes:
      - ./bot/src:/home/node/app/src
      - ./bot/nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    networks: 
      - sail
    command: npm run dev

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: api_bot
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./server/:/var/www
      - ./server/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sail
    links:
      - redis
    command: /usr/bin/supervisord

  webserver:
    image: nginx:alpine
    container_name: webserver_bot
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./server/:/var/www
      - ./server/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - sail

  mongodb:
    container_name: mongodb_server
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - sail
  
  redis:
    image: 'redis:alpine'
    container_name: redis_bot
    ports:
      - "6382:6379"
    networks:
      - sail


networks:
  sail:
      driver: bridge

volumes:
  sailredis:
      driver: local